name: 'napari hub preview page'
description: 'Action for building napari hub preview page.'

inputs:
  hub-ref:
    required: false
    description: 'Ref to use when cloning the napari-hub repo'
    default: 'main'

runs:
  using: 'composite'
  steps:
    - name: Clone plugin repo
      uses: actions/checkout@v2
      with:
        path: plugin
    - name: Clone napari hub repo
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.hub-ref }}
        repository: chanzuckerberg/napari-hub
        path: napari-hub
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with: 
        python-version: '3.8'
    - name: Install plugin
      shell: bash
      run: |
        pip install -e ./plugin
        # push this to a branch on my origin
        # try to use this action from this branch, with hub ref to my branched dev lambda and see if the preview-meta builds
        # check out the build artifact on that action run
    - name: Build plugin
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        pip install -r napari-hub/backend/requirements.txt
        python napari-hub/backend/get_preview.py --local --branch ${{ github.head_ref }} . .

    - name: Copy plugin json to hub frontend repo
      shell: bash
      run: cp preview_meta.json napari-hub/frontend/preview.json

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Get Yarn cache directory path
      shell: bash
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Setup Yarn cache
      uses: actions/cache@v2
      # use this to check for `cache-hit`:
      # (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install dependencies with yarn
      shell: bash
      working-directory: napari-hub/frontend
      run: yarn install

    - name: Build the preview page
      shell: bash
      run: yarn build:preview
      working-directory: napari-hub/frontend
      env:
        BASE_PATH: /${{ github.repository }}/${{ github.event.pull_request.number }}
        PREVIEW: preview.json
        PREVIEW_PULL_REQUEST: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

    - name: Upload preview page artifact
      uses: actions/upload-artifact@v2
      with:
        name: preview-page
        path: napari-hub/frontend/preview
